export const constants = {
  sickLeaveValue: "sick-leave",
  paidLeaveValue: "paid-leave",
  pdf: "application/pdf",
  png: "image/png",
  jpeg: "image/jpeg",
  attachPhoto:
    "Please attach a photo or a scanned copy of your sick leave document",
  typeReason: "Please type in reason",
  submit: "Submit",
  request: "Request",
  type: "Type",
  paidLeave: "Paid leave",
  sickLeave: "Sick leave",
  fileSizeMB: 2,
  minRequestDays: 1,
  saturdayCalendarNumber: 6,
  sundayCalendarNumber: 0,
  mondayCalendarNumber: 1,
  weekendValue: 2,
  users: "users",
  dateFormat: "dd/MM/yyyy",
  history: "History",
  startDate: "Start Date",
  endDate: "End Date",
};
